frase = input("Digite uma frase (sem acentos): ")
frase = frase.upper()
espaco = frase.count(" ")
a = frase.count("A")
e = frase.count("E")
i = frase.count("I")
o = frase.count("O")
u = frase.count("U")
print("A frase tem:")
print(f"{espaco} Espaço(s) em Branco")
print(f"{a} letra(s) A")
print(f"{e} letra(s) E")
print(f"{i} letra(s) I")
print(f"{o} letra(s) O")
print(f"{u} letra(s) U")